title: Ripe Foundation
description: A centralized repository for Ripe Documentation
theme: just-the-docs

url: https://ripe.foundation

callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: purple
  information:
    title: Information
    color: blue
  new:
    title: Tip
    color: green


logo: "img/full_200w.png"
color_scheme: purpledark

nav_external_links:
  - title: Ripe App
    url: https://app.ripecloud.io
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
